### ISSUE TITLE
Links in README doc broken

### ISSUE THREAD

**Issue by pageaffairs** [sitepoint-editors/author-documentation#1]
The links need fixing. One thing I would suggest with file naming, though, is never to have a space in a document name online. It leads to fugly URLs. So rather than

```
articles we publish.md
```

I would strongly recommend

```
articles-we-publish.md
```

Better to address that before the README links, imho.

**Comment by Swader** [comment]
Feel free to submit a PR :)

**Comment by pageaffairs** [comment]
@Swader @AdamRobertsNZ Happy to do that, although I want to check first that the file renaming is OK with you.

**Comment by AdamRobertsNZ** [comment]
@pageaffairs More than happy for you to handle that ;) I'll go through afterwards and make sure the interlinking still works OK - there are a few links between docs that will break with file renaming. I should do this with the editor docs also.

**Comment by pageaffairs** [comment]
OK @AdamRobertsNZ — I've submitted a PR with filename and URL fixes. All the links within the repo should work fine now (including within the various files).

For future reference, links from one file to another look like this:

```
[visit the documentation](quick-tips.md)
```

Links from the README file to other files look like this:

```
[visit the documentation](docs/quick-tips.md)
```

**Comment by AdamRobertsNZ** [comment]
Thanks Ralph, those changes have been merged!

**Comment by pageaffairs** [comment]
Cool. Thanks Adam.
