### ISSUE TITLE
Presenting actions /code.md

### ISSUE THREAD

**Issue by pageaffairs** [sitepoint-editors/author-documentation#2]
> Actions, i.e. 'Click this button', should be italicized.

I've been leaning towards using bold instead (which is also done in SP books). It stands out a bit more clearly, imho. Just throwing this up for discussion. If it stays as italics, I need to change my ways. :D

**Comment by jameshibbard** [comment]
I prefer italics, as bold draws the eye. Bold should be used for important points IMO.
No problems with changing this, though (if deemed necessary).

**Comment by pageaffairs** [comment]
> bold draws the eye
> That's why I like it, as I often find myself scanning a page to find bits of text like that (actions, buttons etc.).

**Comment by AdamRobertsNZ** [comment]
I prefer italics also, for the reason Jim outlined. Better to save bold for when we really need to draw attention to something.

**Comment by pageaffairs** [comment]
OK, outvoted then. But it's usually the actions that I _want_ to stand out, so they're easy to find.

**Comment by AdamRobertsNZ** [comment]
I think you mean, **want** ;) 

But fair enough, this might be something to revisit with the rest of the editorial team!

**Comment by pageaffairs** [comment]
> I think you mean, want ;)

That's not an action, though. An action would be **slap Adam in the face for being cheeky**. :p
