### ISSUE TITLE
spelling grammar language.md

### ISSUE THREAD

**Issue by pageaffairs** [sitepoint-editors/author-documentation#4]
There's an unfinished sentence in the first paragraph:

> If you spot an error with one of your articles (or an article published by someone else)

**Comment by pageaffairs** [comment]
I'd also recommend adding that spelling should be checked against a US dictionary. (Or give me a dollar every time I have to change "colour" to "color" etc. :p

**Comment by pageaffairs** [comment]
In relation to the em dash, it would be worth us deciding on the form we'll all use. I prefer `&mdash;` without gaps either side, but more commonly SitePoint uses an en dash with a gap either side. The advantage of this is that it's easy to create in WordPress:

> I'm about to use a dash -- and there it is.

**Comment by pageaffairs** [comment]
Another section worth adding to this page is Getting Names Right. I'm sick of reading "Javascript", "Github", "markdown" and so on. It's simple to check these things, so the author really should at least make an attempt to get them right. It's basic housekeeping.

**Comment by pageaffairs** [comment]
Sorry for all the entries here, but one further addition would be to stipulate that Markdown files are preferred. There are still HTML and Word files coming in, and it would be good to have an official reminder to submit MD files instead.

**Comment by jameshibbard** [comment]
> Another section worth adding to this page is Getting Names Right. I'm sick of reading "Javascript", "Github", "markdown" and so on. 

Agree with that. We (the JS channel) are looking at ways to automate this.

**Comment by pageaffairs** [comment]
> We … are looking at ways to automate this.

With JS, of course (as everything eventually gets done in JS, right? :p ) Do you mean a solution in the WP editing window, or are thinking of something else?

**Comment by jameshibbard** [comment]
Possibly a GitHub bot, which replies to PRs which contain incorrect formatting.

**Comment by pageaffairs** [comment]
Ah, OK. Cool.

**Comment by AdamRobertsNZ** [comment]
This is great, thanks for all the suggestions @pageaffairs! (One thing, it might be easier to have each suggestion as a separate issue, so I can close the completed ones. Right now I've just added emoji to the ones that are completed.)

I've added the sections you suggested, but I may add an entire doc on submitting drafts which touches on using markdown, final checks etc.

As for the em dash, I'm open to suggestions. I think using double hyphens with no space between the hypens and the words might be easiest to implement. Thoughts?

Also, @jameshibbard - a bot sounds perfect, very excited about that.

**Comment by pageaffairs** [comment]
>  I think using double hyphens with no space between the hypens and the words might be easiest to implement. Thoughts?

@AdamRobertsNZ — The problem I see with that is that is that WP turns -- into an EN dash, which is shorter than an EM, and will be harder to see. The two conventions are either a full-length EM dash with no gaps either side (often preferred) or an EN dash with gaps either side. 

I've just done a bit of reading and experimenting, and have found that three hyphens produce an EM dash, while two produce an EN dash. So if we're going for the EM dash, we just need to ask people to use three hyphens in MD (or they can keyboard insert an EM dash, which is easy on a Mac, or even write it as code—`&mdash;` etc.

**Comment by pageaffairs** [comment]
<img width="377" alt="wp-dash-test" src="https://cloud.githubusercontent.com/assets/1506144/13870740/6a35b10c-ed32-11e5-980f-fa080dcb2188.png">

**Comment by AdamRobertsNZ** [comment]
Cool, have amended the doc to give the three hypen suggestion.

I think it'd make sense to make any further spelling/grammar/language suggestions in the styleguide doc (in the editor docs), since that will eventually replace this doc.

**Comment by pageaffairs** [comment]
Cool, thanks Adam.
